require "rake/clean"

thisdir = File.dirname(__FILE__)
require [thisdir, "..", "project"]. join "/"
require [thisdir, "compile"].join "/"

testfiles = FileList.new("test_*.cu")
runfiles = testfiles.ext("")

CLOBBER.include(runfiles)

runfiles.each do |runfile|
  file runfile => "#{runfile}.cu" do |t|
    # src -> bin
    compile(t.prerequisites[0], t.name)
  end
end

task :compile => runfiles

task :run_test => :compile do
  runfiles.each do |runfile|
    sh "./#{runfile}"
  end
end
