Import('env')

my_env = env.Clone()

LIBS = ''
common_libs = ['pthread', 'gtest']
my_env.Append(LIBS = common_libs)

my_env.Program('bphcuda', 'bphcuda.cu', LIBS)
my_env.Program('thrusting', 'thrusting.cu', LIBS)
