require "bphcuda"

cxx = Bphcuda.make_default_compiler
cxx.use_real_precision("float")
cxx.optimize(2)
cxx << "-Xcompiler -march=i686"
cxx << "-use_fast_math"
cxx << "-Xcompiler -Wall"
#cxx << "-ftz=false"
cxx << "-Xcompiler -mieee-fp"
#cxx.enable_debug_mode(true)
dirs = [
"wallshock_x",
"wallshock_y",
"wallshock_z",
"shocktube_x",
"shocktube_y",
"sjogreen_x",
"noh2d_xy"]

dirs.each do |d|
  cxx.make_compile_task(d)
end
