require "rake/clean"

["make_compile_task", "compile_option"].each do |f|
  require "build/thrusting/#{f}"
end

["def_compile"].each do |f|
  require "build/bphcuda/#{f}"
end

cc = BPHCUDA_CXX
p cc

# cc = with_mode(cc, "release")
cc += " -O3"

make_compile_task(cc, "wallshock")
