require "rake/clean"

["make_compile_task", "compile_option"].each do |f|
  require "thrusting/build/#{f}"
end

["def_compile"].each do |f|
  require "bphcuda/build/#{f}"
end

["gtest"].each do |f|
  require "thrusting/build/path/#{f}"
end

cc = BPHCUDA_CXX

cc = with_mode(cc, "debug")
cc = use_gtest(cc)

make_compile_task(cc, "gtest")

dirname = "gtest"

namespace :regress do
  task :on_host => "#{dirname}/all_on_host.bin" do |t|
    system "#{dirname}/all_on_host.bin 1> host.regression"
  end
  
  task :on_device => "#{dirname}/all_on_device.bin" do |t|
    system "#{dirname}/all_on_device.bin 1> device.regression"
  end
  
  task :on_omp => "#{dirname}/all_on_omp.bin" do |t|
    system "#{dirname}/all_on_omp.bin 1> omp.regression"
  end
  
  desc("Run all the test on all devices")
  task :on_all => [:on_host, :on_device, :on_omp]
end
