
A="targets/cpp_host_cuda_device_release"

T="time"
P="plot"
F="figure"

sh "mkdir -p #{T} #{P} #{F}"

desc "wallshock test"
task "wallshock_x" do
  sh "#{A}/wallshock_x 4000 1000 2 0.5 #{P}/wallshock_x.dat #{T}/wallshock_x.dat"
end

desc "shocktube test"
task "shocktube_x" do
  sh "#{A}/shocktube_x 500 1000 2 0.15 #{P}/shocktube_x.dat #{T}/shocktube_x.dat"
end

desc "Sjogreen test"
task "sjogreen_x" do
  sh "#{A}/sjogreen_x 4000 1000 2 0.1 7 #{P}/sjogreen_x.dat #{T}/sjogreen_x.dat"
end

desc "Noh test (2d)"
task "noh2d_xy" do
  sh "#{A}/noh2d_xy 100 100 2 0.5 #{P}/noh2d_xy.dat #{T}/noh2d_xy.dat"
end


$LOAD_PATH.push("gp/lib")
$LOAD_PATH.push("script")

require "gp"

require "wallshock_x"
require "shocktube_x"
require "sjogreen_x"
require "noh2d_xy"

desc "Generate Figures"
task "figures" do
  Wallshock.new("wallshock_x").draw
  Shocktube.new("shocktube_x").draw
  Sjogreen.new("sjogreen_x").draw 
  Noh2d.new("noh2d_xy").draw
end

desc "run all tests"
task :run_tests => ["wallshock_x", "shocktube_x", "sjogreen_x", "noh2d_xy"]

desc "Run Everything"
task :all => [:run_tests, "figures"]
