a="targets/cpp_host_cuda_device_release"
b="testdata"

desc "wallshock test"
task "wallshock_x" do
  sh "#{a}/wallshock_x 4000 1000 2 0.5 #{b}/wallshock_x_plot.dat #{b}/wallshock_x_time.dat"
end

desc "shocktube test"
task "shocktube_x" do
  sh "#{a}/shocktube_x 500 1000 2 0.15 #{b}/shocktube_x_plot.dat #{b}/shocktube_x_time.dat"
end

desc "Sjogreen test"
task "sjogreen_x" do
  sh "#{a}/sjogreen_x 4000 1000 2 0.1 7 #{b}/sjogreen_x_plot.dat #{b}/sjogreen_x_time.dat"
end

desc "Noh test (2d)"
task "noh2d_xy" do
  sh "#{a}/noh2d_xy 100 100 2 0.5 #{b}/noh2d_xy_plot.dat #{b}/noh2d_xy_time.dat"
end

desc "run all tests"
task :all => ["wallshock_x", "shocktube_x", "sjogreen_x", "noh2d_xy"]
