Import('env')

# aaa
my_env = env.Clone()

my_env.Program('noh2d_xy', 'noh2d_xy.cu')
my_env.Program('shocktube_x', 'shocktube_x.cu')
my_env.Program('sjogreen_x', 'sjogreen_x.cu')
my_env.Program('wallshock_x', 'wallshock_x.cu')
