require "bphcuda"

file "shell_rand_map.h" do |t|
  include Bphcuda
  nz = 10
  nangle = 10
txt =
"""
#pragma once
#include <thrusting/real.h>
namespace {
  using namespace thrusting;
}
namespace bphcuda {
namespace detail {
size_t SHELL_RAND_MAP_SIZE = #{nz*nangle};
#{make_shell_rand_map(nz,nangle)}
} // END detail
} // END bphcuda

"""
  f = File.open(t.name, "w")
  f.write(txt)
  f.close
end

CLOBBER.include("shell_rand_map.h")

task :build => "shell_rand_map.h"

