require "rake/clean"

hs = FileList["*.h"].exclude("all.h")

file "all.h" => hs do
  f = File.open("all.h", "w")
  f.write("#pragma once\n")
  txt = hs.map { |f| "#include \"#{f}\"" }.join "\n"
  f.write(txt)
  f.close
end
