require "rake/clean"

task :mk_typedef => ["mk_int.h", "mk_real.h"]

file "mk_int.h" => "mk_int.rb" do |t|
  sh "ruby #{t.prerequisites[0]} > #{t.name}"
end

file "mk_real.h" => "mk_real.rb" do |t|
  sh "ruby #{t.prerequisites[0]} > #{t.name}"
end

CLOBBER.include("mk_real.h", "mk_int.h")
